## Balanced Stroke prediction dataset

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix, precision_score, recall_score
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [9]:
df = pd.read_csv("stroke_risk_dataset.csv")
df.head()

,Chest Pain,Shortness of Breath,Irregular Heartbeat,Fatigue & Weakness,Dizziness,Swelling (Edema),Pain in Neck/Jaw/Shoulder/Back,Excessive Sweating,Persistent Cough,Nausea/Vomiting,High Blood Pressure,Chest Discomfort (Activity),Cold Hands/Feet,Snoring/Sleep Apnea,Anxiety/Feeling of Doom,Age,Stroke Risk (%),At Risk (Binary)
0,0,1,1,1,0,0,0,1,1,1,0,1,1,0,0,54,58.0,1
1,0,0,1,0,0,1,0,0,0,0,1,0,1,1,0,49,40.5,0
2,1,0,0,1,1,1,0,0,1,0,0,0,0,1,0,62,52.0,1
3,1,0,1,1,0,1,1,1,1,1,1,0,0,0,0,48,60.0,1
4,0,0,1,0,0,1,0,1,0,1,1,0,0,1,1,61,56.5,1

In [11]:
df.info()
df.tail()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Chest Pain                      70000 non-null  int64
 1   Shortness of Breath             70000 non-null  int64
 2   Irregular Heartbeat             70000 non-null  int64
 3   Fatigue & Weakness              70000 non-null  int64
 4   Dizziness                       70000 non-null  int64
 5   Swelling (Edema)                70000 non-null  int64
 6   Pain in Neck/Jaw/Shoulder/Back  70000 non-null  int64
 7   Excessive Sweating              70000 non-null  int64
 8   Persistent Cough                70000 non-null  int64
 9   Nausea/Vomiting                 70000 non-null  int64
 10  High Blood Pressure             70000 non-null  int64
 11  Chest Discomfort (Activity)     70000 non-null  int64
 12  Cold Hands/Feet                 70000 non-null  int64
 13  Snoring/Sleep Apnea             70000 non-null  int64
 14  Anxiety/Feeling of Doom         70000 non-null  int64
 15  Age                             70000 non-null  int64
 16  Stroke Risk (%)                 70000 non-null  float64
 17  At Risk (Binary)                70000 non-null  int64
dtypes: float64(1), int64(17)
memory usage: 9.6 MB

,Chest Pain,Shortness of Breath,Irregular Heartbeat,Fatigue & Weakness,Dizziness,Swelling (Edema),Pain in Neck/Jaw/Shoulder/Back,Excessive Sweating,Persistent Cough,Nausea/Vomiting,High Blood Pressure,Chest Discomfort (Activity),Cold Hands/Feet,Snoring/Sleep Apnea,Anxiety/Feeling of Doom,Age,Stroke Risk (%),At Risk (Binary)
69995,1,0,0,0,0,0,0,1,0,1,1,1,0,0,1,18,30.0,0
69996,0,0,0,1,0,1,0,1,0,0,0,1,1,1,0,24,33.0,0
69997,1,1,0,1,1,1,0,0,0,0,1,0,0,0,0,49,45.5,0
69998,0,1,1,1,1,0,0,0,0,0,0,1,1,1,0,45,48.5,0
69999,0,1,0,0,0,0,0,1,1,1,1,1,0,1,0,74,63.0,1